Repository zitadel/oidc, pull requests merged in 2024-04, with the labels that each got.

#571 feat: return oidc.Error in case of call token failure
  pkg/client/client.go
  pkg/http/http.go
Labels: os-contribution, auth

#582 fix: Fail safe, if optional endpoints are not given
  pkg/client/client.go
  pkg/client/errors.go
Labels: os-contribution

#591 docs: Fixes typos in GoDoc and comments
  example/server/exampleop/op.go
  pkg/client/rp/relying_party.go
Labels: os-contribution

#579 feat: Added the ability to verify ID tokens using the value of id_token_signing_alg_values_supported retrieved from DiscoveryEndpoint
  pkg/client/integration_test.go
  pkg/client/rp/relying_party.go
Labels: waiting, os-contribution

#593 fix: fetchRemoteKeys context to include in request
  pkg/client/rp/jwks.go
Labels: os-contribution
